### ISSUE TITLE
[2-1] Main page - Header, Content, Footer 나누기

### ISSUE THREAD

**Issue by danielsychoo** [codestates/cloud-bookstore-client#12]
## ISSUE
Group: `client`
Type: `feature`
Detail: 

1. 3개 div 배치

## Difficulty: 스스로 느낀 난이도를 작성
* [x] low

## Todo: 실제로 작업한 내용을 작성
* [x] 1. Footer 부분을 하나의 component로 분리
* [x] 2. Landing page를 제외한 모든 page 배경 white로 설정
* [x] 3. 배치 진행하며 UserNav, CategoryNav, mainWrapper 작업실행

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`2.5hr`
