### ISSUE TITLE
[2-2] Main page - Header 구축

### ISSUE THREAD

**Issue by danielsychoo** [codestates/cloud-bookstore-client#13]
## ISSUE
Group: `client`
Type: `feature`
Detail: 

1. 상단 div와 하단 Nav div로 나눔
2. 상단 div
    - 좌측 logo onClick시에 Main page 새로고침
    - 우측 로그인/회원가입 -> modal창으로 띄움
3. 하단 div
    - 좌측 카테고리 탭 : '판타지', '무협', '로맨스', 'MY'
    - 우측 검색 탭 : Google search library (api 존재함)

> 참고자료
> https://www.npmjs.com/package/react-facebook-login

## Difficulty: 스스로 느낀 난이도를 작성
* [x] middle  

## Todo: 실제로 작업한 내용을 작성
* [x] 1. Landingpage와 Mainpage의 body color 관련 이슈 재설정
* [x] 2. userNav와 categoryNav 구축 및 css 설정
* [x] 3. categoryNav의 각 category들 onclick시 변경되도록 state 및 css 설정
* [x] 4. react-icons library 설치 하고 icon 사용
* [x] 5. Login modal창 만들고 state를 통해 modal 띄웠다 없어졌다 하게 설정

> 추후 코드 확인시 함수를 전달받는 자식 컴포넌트에서 해당 함수에 대한
> interface가 존재해야 오류가 발생하지 않는다고 (typescript에서 오류로 인식)
> 주석달아놓은 부분 확인필요. (앞으로도 필요한 부분이므로 알아둘 필요 있음)
> 해당주석 -> pages/modal/LoginModal.tsx 의 5~8번째 줄

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`4hr`
