### ISSUE TITLE
[2-3] Main page - Content 구축

### ISSUE THREAD

**Issue by danielsychoo** [codestates/cloud-bookstore-client#14]
## ISSUE
Group: `client`
Type: `feature`
Detail: 

1. 5개 div로 나눔
2. slider, 웹소설 랭킹, 판타지, 무협, 로맨스

## Difficulty: 스스로 느낀 난이도를 작성
* [x] middle  

## Todo: 실제로 작업한 내용을 작성
* [x] 1. slider부분 구축 및 css 구현
* [x] 2. mainPage와 novelList 구축
* [x] 3. favicon 업데이트 및 CRA시에 생성되었던 필요없는 파일들 제거
* [x] 4. data 테스트를 위해 fakeData.js 생성 (src/asset/fakeData)
* [x] 5. newObject와 completeObject 구축

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`4hr`
