### ISSUE TITLE
[2-5] Main page - Content 웹소설랭킹, 판타지, 무협, 로맨스

### ISSUE THREAD

**Issue by danielsychoo** [codestates/cloud-bookstore-client#16]
## ISSUE
Group: `client`
Type: `feature`
Detail: 

1. 구름 순서로 랭킹설정
2. 8개 까지 표출
3. sort이용해 순서세우고 map으로 (미리 mockup으로 css 잡아놔야 함)
4. 작품 onClick시에
    - Novel 이름, 작가 이름, Novel 댓글갯수, 구름 갯수, 관심 갯수, description,
    thumbnail, (로그인상태라면) 마지막으로 읽은 횟차, 구매한 회차,
    해당 Novel의 댓글리스트, 해당 Novel의 category
    모든 회차의 (thumbnail, title, 구름갯수, new, 완결)
5. [특이사항] 판타지, 무협, 로맨스 의 경우 '더보기'누르면 해당 페이지로
     Link

## Difficulty: 스스로 느낀 난이도를 작성
* [x] middle  

## Todo: 실제로 작업한 내용을 작성
* [x] 1. MainPage내부의 기능들 component 분리
            - novelList component
            - mainPageNovelWrapper component
* [x] 2. Props를 통해 fakeData NovelList까지 넘겨 출력
* [x] 3. new tag -> 오늘 날짜와 createdAt을 비교하여 출력
* [x] 4. complete tag -> props의 complete가 true일 때만 출력
* [x] 5. author 길이 ... -> slice로 length 확인해 삼항연산으로 출력
* [x] 6. subject 길이 ... -> slice로 length 확인해 삼항연산으로 출력

> src/Mainpage.tsx 에서
> 추후 axios get으로 받아온 실제 data만 fakeData의 대체로 넣어주면 완료

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`3hr`
