### ISSUE TITLE
[3-1] Category - Category 판타지

### ISSUE THREAD

**Issue by danielsychoo** [codestates/cloud-bookstore-client#17]
## ISSUE
Group: `client`
Type: `feature`
Detail: 

1. 드롭다운메뉴
    - 업데이트순, 제목순, 구름순, 관심순
    - 해당 순서 onClick시 axios-get 요청
    - 받은 res를 기준으로 해당 페이지 re-render
2. 작품 4개씩 늘어뜨리기

<i>[advanced - 작품 16개까지만 띄우고 아래 게시판 1,2,3,4,5 ...]</i>

## Difficulty: 스스로 느낀 난이도를 작성
* [x] high

## Todo: 실제로 작업한 내용을 작성
* [x] 1. FantasyCategory component 만들고 route 처리
* [x] 2. selectBox에 따른 sort 처리
* [x] 3. new obejct 위치 변경 및 response css 설정

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`4hr`
