### ISSUE TITLE
[6-7] Novel details - 소설읽기 페이지 구축

### ISSUE THREAD

**Issue by danielsychoo** [codestates/cloud-bookstore-client#183]
## ISSUE
Group: `client`
Type: `feature`
Detail: 

## Difficulty: 스스로 느낀 난이도를 작성
* [x] high

## Todo: 실제로 작업한 내용을 작성
* [x] 1. App에서 NovelReadStage로 data가 direct로 흐르기 때문에 data의 종합을 필수적으로 App에서 해야 됨을 인지
* [x] 2. MainPage에서 관리하던 전체 데이터들과 axios관련 함수 및 state들 App으로 이동 후 재연결 실시
* [x] 3. specificEpisode를 특정하기위해 state 만들고 App - MainPage - NovelInfo - EpisodeList - PurchaseCheckList에서 뽑아옴
* [x] 4. 3에서 뽑아온 인자를 기준으로 specificEpisodeData를 get하여 해당 data를 props로 NovelReadStage.tsx로 내려줌
* [x] 5. 내려준 data기준으로 novelInfoComponents/EpisodeListComponents/NovelReadStage 구축 후 연결

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`4hr`
