### ISSUE TITLE
[4-5] Novel list - 작품 회차

### ISSUE THREAD

**Issue by danielsychoo** [codestates/cloud-bookstore-client#24]
## ISSUE
Group: `client`
Type: `feature`
Detail: 

1. 작품회차 옆에 ()에 회차의 length로 표기
2. 작품은 무료, 유료로 나뉨, 유료는 어두운 검정으로 덮여있음
3. 유료작품 클릭시 구름결제관련 modal 띄움
4. 작품은 10개씩 출력되고 아래에 1,2,3,4 게시판 기능

> 참고자료
> https://chanhuiseok.github.io/posts/react-13/

## Difficulty: 스스로 느낀 난이도를 작성
* [x] high

## Todo: 실제로 작업한 내용을 작성
* [x] 1. 작품 회차 갯수 보여주기
* [x] 2. 유료는 opacity로 처리
* [x] 3. 구매 목록에 따라서 opactiy 처리

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`2d`
