### ISSUE TITLE
[6-2] My page - 최근 본 작품

### ISSUE THREAD

**Issue by danielsychoo** [codestates/cloud-bookstore-client#29]
## ISSUE
Group: `client`
Type: `feature`
Detail: 

1. 최근 본 작품, 관심작품은 전부다 일렬로 띄움
    - 회차목록 button click시 Novel-list로 Link

## Difficulty: 스스로 느낀 난이도를 작성
* [x] middle  

## Todo: 실제로 작업한 내용을 작성
* [x] History Novel 을 담아주는 컨테이너 컴포넌트 작성
* [x] History Novel Card를 만들어 주는 컴포넌트를 작성
* [x] state 를 mainPage에서 변경하는 메소드 생성

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`0.5hr` , `1hr`, `1.5hr`, `2hr`, `2.5hr`, `3hr`, `3.5hr`, `4hr`
