### ISSUE TITLE
[0-2] SR - esLint, prettier 설정

### ISSUE THREAD

**Issue by danielsychoo** [codestates/cloud-bookstore-client#35]
## ISSUE
Group: `SR`
Type: `setting`
Detail: 

repo에 esLint와 prettier 설정 및 boiler plate 작업

## Difficulty: 스스로 느낀 난이도를 작성
* [x] middle  

## Todo: 실제로 작업한 내용을 작성
* [x] 1. CRA - typescript
* [x] 2. eslint 설치 및 setting
* [x] 3. prettier 설치 및 setting
* [x] 4. husky v5 설치 및 pre-commit hooks 설정

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`4hr`
