### ISSUE TITLE
[1-1] Landing page - Header, Content, Footer 나누기

### ISSUE THREAD

**Issue by danielsychoo** [codestates/cloud-bookstore-client#5]
## ISSUE
Group: `client`
Type: `feature`
Detail: 

1. 전체 <div>와 내부 3 element
2. Grid 방법으로 정렬
3. 각각 1vh로 (Header, Content1, Content2, Content3, Footer)

> 참고자료
> https://www.kakaopagecorp.com/?lang=ENG
> https://css-tricks.com/books/greatest-css-tricks/scroll-animation/

## Difficulty: 스스로 느낀 난이도를 작성
* [x] low

## Todo: 실제로 작업한 내용을 작성
* [x] 1. 디자인에 사용될 png들 asset dir에 넣어둠
* [x] 2. css초기화를 위해 nomalize.css library설치하고 index.tsx에 css초기화 적용
* [x] 3. 모든 폰트 NotoSansKR이므로 index.css에 해당 폰트 전체적용
* [x] 4. 버튼 등에 대한 누르는 느낌 애니메이션 index.css에 전체적용
* [x] 5. landing page 각 부분의 크기와 배치 디자인 시안에 따라 적용

(웹 먼저 완성 후 모바일 고려하기로 했으므로 Grid 고려하지 않음. 어차피 사이즈만 줄인다고 했으므로 큰 문제 없음)
(1페이지당 1화면이었던 컨셉이 바뀌었으므로 1vh로 height 맞추지 않았음)

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`1.5hr`
