### ISSUE TITLE
[2-6] Main page - 반응형 적용

### ISSUE THREAD

**Issue by danielsychoo** [codestates/cloud-bookstore-client#52]
## ISSUE
Group: `client`
Type: `feature`
Detail: 

Main page 반응형 적용

## Difficulty: 스스로 느낀 난이도를 작성
* [x] high

## Todo: 실제로 작업한 내용을 작성
* [x] 1. 컴퓨터에서 창 줄였을 시 (75%-50%) 창 대응되도록 설정
* [x] 2. 컴퓨터에서 창 줄였을 시 (50%-25%) 창 대응되도록 설정
* [x] 3. 아이패드에서 실행 시 창 대응되도록 설정
* [x] 4. 아이폰X에서 실행 시 창 대응되도록 설정
* [x] 5. 아이폰6시리즈 이상에서 실행 시 창 대응되도록 설정
* [x] 6. 갤럭시폴드에서 실행 시 창 대응되도록 설정
* [x] 7. 갤럭시5시리즈 이상에서 실행 시 창 대응되도록 설정 
* [x] 8. (login Modal만 추가사항) 애매한 구간 (100%-75%) 창 대응되도록 설정
* [x] 9. (login Modal만 추가사항) 애매한 구간 (25%-10%) 창 대응되도록 설정

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`4hr`
