### ISSUE TITLE
[1-3] Landing page - Content 구축

### ISSUE THREAD

**Issue by danielsychoo** [codestates/cloud-bookstore-client#7]
## ISSUE
Group: `client`
Type: `feature`
Detail: 

1. 내부에서 div 3개
2. display: flex
3. flex-direction: row
4. 각각의 div의 margin-top 조정하여 높이조절

## Difficulty: 스스로 느낀 난이도를 작성
* [x] middle  

## Todo: 실제로 작업한 내용을 작성
* [x] 1. BestNovel Wrapper 부분 완성
* [x] 2. 1번의 과정 중 fade animation을 넣기위해 AOS library를 설치하고 적용 
* [x] 3. write novel Wrapper 부분 완성
* [x] 4. cloud-bookstore Func 부분 완성

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`4hr`
