### ISSUE TITLE
[7-2] Setting -Cloud 사용내역-차감

### ISSUE THREAD

**Issue by paigekim29** [codestates/cloud-bookstore-client#71]
## ISSUE
Group: `client`
Type: `bug`, `feature`
Detail: 

 Setting -Cloud 사용내역-차감

## Difficulty: 스스로 느낀 난이도를 작성 
* [x] high

## Todo: 실제로 작업한 내용을 작성
* [x] 1. router 처리
* [x] 2. props로 내려서 state 관리 
* [x] 3. axios.get 보내기
* [x] 4. calendar axios.post 보내기
* [x] 5. 반응형 처리 

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`1.5d`
