### ISSUE TITLE
[7-3] Setting -nickname 수정

### ISSUE THREAD

**Issue by paigekim29** [codestates/cloud-bookstore-client#72]
## ISSUE
Group: `client`
Type: `feature`
Detail: 

Setting -nickname 수정

## Difficulty: 스스로 느낀 난이도를 작성
* [x] middle  

## Todo: 실제로 작업한 내용을 작성
* [x] 1. toggle 형식으로 닉네임 수정 모달 생성
* [x] 2. 반응형 및 css 코드 구현
* [x] 3. 나가기 버튼 아이콘 생성 및 코드 구현

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`4hr`
