### ISSUE TITLE
[1-5] Landing page - Logo 구현

### ISSUE THREAD

**Issue by danielsychoo** [codestates/cloud-bookstore-client#9]
## ISSUE
Group: `client`
Type: `feature`
Detail: 

1. div로 구름책방 로고 박기
2. 로고 클릭시 현재 페이지 새로고침

## Difficulty: 스스로 느낀 난이도를 작성
* [x] low

## Todo: 실제로 작업한 내용을 작성
* [x] 1. Mainpage.tsx 생성
* [x] 2. react-router-dom 설치 후 프로젝트 전반에 적용
* [x] 3. logo 클릭시 Landing page가 re-render 되도록 적용

## Total Hours: 스스로 끝내는데까지 걸린 시간을 작성
`1hr`
